server:
  port: 8888

logging:
  config: classpath:log4j2-spring.xml

spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filter:
        config:
          enabled: true